import { type AppType, type AppProps } from "next/app";
import Head from 'next/head';
import { MantineProvider } from '@mantine/core';
import { api } from "~/utils/api";

import "~/styles/globals.css";

const MyApp: AppType = ({ Component, pageProps }:AppProps) => {
  return   <>
  <Head>
    <title>Book Club</title>
    <meta name="description" content="Generated by create-t3-app" />
    <link rel="icon" href="/favicon.ico" />
    <meta name="viewport" content="minimum-scale=1, initial-scale=1, width=device-width" />
  </Head>

  <MantineProvider
    withGlobalStyles
    withNormalizeCSS
    theme={{
      /** Put your mantine theme override here */
      colorScheme: 'light',
    }}
  >
    <Component {...pageProps} />
  </MantineProvider>
</>;
};

export default api.withTRPC(MyApp);