import styles from './index.module.css';
import { type NextPage } from 'next';
import Head from 'next/head';
import {
  Card,
  Text,
  Title,
  Container,
  Group,
  Button,
  Image,
  List
} from '@mantine/core';
import Link from 'next/link';

import BookCard from '../components/book-card';

const Home: NextPage = () => {
  const members = [
    { name: 'Nikita Khristinin' },
    { name: 'Marusia Urusova' },
    { name: 'Ania Tischenko' }
  ];
  return (
    <>
      <Head>
        <title>BookClub</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container className={styles.app}>
        <Container className={styles.container}>
          <header className={styles.header}>
            <Group position="apart" w="100%">
              <Group>
                <Title size="20px">
                  <Link href={'/'}>Book Club</Link>
                </Title>
              </Group>
              <Group>
                <Button>Login</Button>
              </Group>
            </Group>
          </header>
          <main className={styles.main}>
            <Group position="apart" mb="40px">
              <Card w="160px" radius="xl" shadow="lg">
                <Text align="center">2 years 7 month</Text>
              </Card>
              <Card w="160px" radius="xl" shadow="lg">
                <Text align="center">8 members</Text>
              </Card>
              <Card w="160px" radius="xl" shadow="lg">
                <Text align="center">31 meetings</Text>
              </Card>
            </Group>

            <Container className={styles.choosingSection} p="0">
              <Group className={styles.choosingGroup}>
                <Title className={styles.title} size="sm">
                  Next Meeting:
                </Title>
                <Card shadow="xl" className={styles.nextChoosed}>
                  <Group className={styles.nextMeetingCover}>
                    <Image
                      src="https://picsum.photos/150/220"
                      alt="next meeting cover"
                    />
                  </Group>

                  <Group className={styles.nextMeetingInfo}>
                    <Text mb="40px" size="sm">
                      Name book
                    </Text>
                    <Text mb="40px" size="sm">
                      Choosen by: <Link href="/">Lera Khristinina</Link>
                    </Text>
                    <Text size="sm">See you DD month YYYY</Text>
                  </Group>
                </Card>
              </Group>
              <Group className={styles.choosingGroup}>
                <Title className={styles.title}>Next Chosing Member:</Title>
                <Card shadow="xl" className={styles.nextChoosed}>
                  <List className={styles.members}>
                    {members.map((member, index) => {
                      return (
                        <List.Item className={styles.firstMeber} key={index}>
                          <Link href="/">{member.name}</Link>
                        </List.Item>
                      );
                    })}
                    <List.Item>
                      <Link href='/members'>...</Link>
                    </List.Item>
                  </List>
                </Card>
              </Group>
            </Container>

            <Container p="0">
              <Title className={styles.title} size="sm">
                Last Three Meetings
              </Title>
              <Group mb="40px" position="apart">
                <BookCard></BookCard>
                <BookCard></BookCard>
                <BookCard></BookCard>
              </Group>
              <Link href='/'>See all past meetings...</Link>
            </Container>
          </main>
          <footer className={styles.footer}>
            <Group position="right">
              <Group position="left">
                <Text>
                  Created by{' '}
                  <i>
                    <Link href="https://github.com/ValeriaKhristinina">
                      Lera Khristinina
                    </Link>
                  </i>
                </Text>
              </Group>
            </Group>
          </footer>
        </Container>
      </Container>
    </>
  );
};

export default Home;
